import { Product, ProductCategory, Brand, Order, Customer, Enquiry, Coupon, BlogPost, PageContent, StoreSettings, RedirectRule } from './types';

export const initialCategories: ProductCategory[] = [
  {
    id: 'cat-1',
    name: 'Pharmacy Refrigerators',
    slug: 'pharmacy-refrigerators',
    description: 'Medical grade cold storage and pharmacy temperature-controlled refrigerators (2–8°C).',
    image: '/images/original/Fridges-Pharmacy_Haier_HYC-309.png',
    displayOrder: 1,
    productCount: 18,
    seoTitle: 'Pharmacy Refrigerators UAE - FastonMed Medical Cold Storage',
    seoDescription: 'Explore Haier Biomedical and top pharmaceutical cold storage refrigerators in UAE.'
  },
  {
    id: 'cat-2',
    name: 'ICU Equipment',
    slug: 'icu-equipment',
    description: 'Critical care ventilators, infusion pumps, syringe drivers, and defibrillators.',
    image: '/images/original/genaral-equipments-1.jpeg',
    displayOrder: 2,
    productCount: 34,
    seoTitle: 'ICU & Critical Care Equipment UAE - FastonMed',
    seoDescription: 'High performance ICU equipment for hospitals and intensive care units across UAE.'
  },
  {
    id: 'cat-3',
    name: 'Patient Monitoring',
    slug: 'patient-monitoring',
    description: 'Multi-parameter monitors, vital signs monitors, ECG machines, and pulse oximeters.',
    image: '/images/original/genaral-equipments-1.jpeg',
    displayOrder: 3,
    productCount: 42,
    seoTitle: 'Patient Monitoring Systems Dubai UAE',
    seoDescription: 'Advanced patient monitors with ECG, SpO2, NIBP, and IBP monitoring modules.'
  },
  {
    id: 'cat-4',
    name: 'Dental Equipment',
    slug: 'dental-equipments',
    description: 'Comprehensive dental treatment units, dental chairs, autoclaves, and handpieces.',
    image: '/images/original/dental-chair-1.jpeg',
    displayOrder: 4,
    productCount: 29,
    seoTitle: 'Dental Chairs & Equipment UAE - FastonMed',
    seoDescription: 'Ergonomic dental delivery systems and sterilization equipment for dental clinics in Dubai.'
  },
  {
    id: 'cat-5',
    name: 'Dermatology Equipment',
    slug: 'dermatology-equipment',
    description: 'Aesthetic laser devices, cryotherapy, electrosurgical units, and skin diagnostics.',
    image: '/images/original/WhatsApp-Image-2025-06-28-at-18.29.38-1-1.jpeg',
    displayOrder: 5,
    productCount: 21,
    seoTitle: 'Dermatology & Aesthetic Medical Equipment UAE',
    seoDescription: 'Advanced clinical dermatology machines and aesthetic devices supplied in Dubai.'
  },
  {
    id: 'cat-6',
    name: 'ENT Equipment',
    slug: 'ent-equipments',
    description: 'ENT treatment workstations, video otoscopes, headlamps, and diagnostic audiometers.',
    image: '/images/original/ent-1.jpeg',
    displayOrder: 6,
    productCount: 16,
    seoTitle: 'ENT Treatment Systems & Diagnostics UAE',
    seoDescription: 'Professional otolaryngology equipment for clinics and surgery centers in UAE.'
  },
  {
    id: 'cat-7',
    name: 'Gynecology Equipment',
    slug: 'labor-room-equipments',
    description: 'Obstetric delivery beds, fetal monitors, colposcopes, and infant warmers.',
    image: '/images/original/gynocology-1.jpeg',
    displayOrder: 7,
    productCount: 25,
    seoTitle: 'Gynecology & Labor Room Medical Equipment UAE',
    seoDescription: 'Premium obstetric and maternal care equipment for UAE maternity wards.'
  },
  {
    id: 'cat-8',
    name: 'Laboratory Equipment',
    slug: 'laboratory-equipment',
    description: 'Centrifuges, biochemistry analyzers, lab incubators, microscopes, and cold storage.',
    image: '/images/original/laborotory-equipments-1.jpeg',
    displayOrder: 8,
    productCount: 38,
    seoTitle: 'Clinical Laboratory Equipment UAE',
    seoDescription: 'Diagnostic laboratory equipment and medical centrifuges supplied across Dubai and Abu Dhabi.'
  },
  {
    id: 'cat-9',
    name: 'Ophthalmology Equipment',
    slug: 'ophthalmology-equipments',
    description: 'Slit lamps, ophthalmic chairs, refractometers, and surgical microscopes.',
    image: '/images/original/ofthemology-1.jpeg',
    displayOrder: 9,
    productCount: 19,
    seoTitle: 'Ophthalmology Eye Care Equipment UAE',
    seoDescription: 'High precision optical diagnostic and eye exam equipment for ophthalmic practices.'
  },
  {
    id: 'cat-10',
    name: 'Physiotherapy Equipment',
    slug: 'physiotherapy-equipments',
    description: 'TECAR therapy units, electrotherapy, ultrasound therapy, and traction tables.',
    image: '/images/original/phsyotherapy-1.jpeg',
    displayOrder: 10,
    productCount: 31,
    seoTitle: 'Physiotherapy & Rehabilitation Devices UAE',
    seoDescription: 'Rehabilitation, electrotherapy, and physiotherapy devices for sports clinics.'
  },
  {
    id: 'cat-11',
    name: 'Radiology Equipment',
    slug: 'radiology-equipments',
    description: 'Portable X-ray systems, digital radiography detectors, and ultrasound scanners.',
    image: '/images/original/radiology-1.jpeg',
    displayOrder: 11,
    productCount: 15,
    seoTitle: 'Medical Radiology & Imaging Equipment UAE',
    seoDescription: 'Reliable X-ray and diagnostic ultrasound systems for imaging centers in UAE.'
  },
  {
    id: 'cat-12',
    name: 'Hospital Furniture',
    slug: 'hospital-furniture',
    description: 'Electric hospital beds, emergency crash carts, medical trolleys, and examination couches.',
    image: '/images/original/WhatsApp-Image-2025-06-28-at-18.29.37-1.jpeg',
    displayOrder: 12,
    productCount: 45,
    seoTitle: 'Hospital Furniture & Medical Beds UAE',
    seoDescription: 'Durable ergonomic hospital beds, surgical trolleys, and patient seating.'
  },
  {
    id: 'cat-13',
    name: 'Consumables & Disposables',
    slug: 'consumables-and-disposables',
    description: 'Surgical gloves, syringes, IV cannulas, sterilization pouches, and wound dressings.',
    image: '/images/original/consumables-1.jpeg',
    displayOrder: 13,
    productCount: 110,
    seoTitle: 'Medical Consumables and Disposables UAE',
    seoDescription: 'Wholesale sterile disposable medical supplies for hospitals and outpatient centers.'
  },
  {
    id: 'cat-14',
    name: 'Accessories',
    slug: 'accessories',
    description: 'SpO2 sensors, NIBP cuffs, ECG cables, transducers, and power adapters.',
    image: '/images/original/accessories-1.jpeg',
    displayOrder: 14,
    productCount: 68,
    seoTitle: 'Medical Device Accessories & Cables UAE',
    seoDescription: 'Replacement sensors, leadwires, cuffs, and probes for patient monitors in UAE.'
  }
];

export const initialBrands: Brand[] = [
  {
    id: 'b-1',
    name: 'Haier Biomedical',
    slug: 'haier-biomedical',
    description: 'Global leader in medical cold chain solutions, pharmacy refrigerators, and biological storage.',
    productCount: 18,
    logo: 'https://www.fastonmed.com/wp-content/uploads/2026/09/Fridges-Pharmacy_Haier_HYC-309.png'
  },
  {
    id: 'b-2',
    name: 'Mindray',
    slug: 'mindray',
    description: 'Worldwide provider of patient monitoring, medical imaging, and in-vitro diagnostic products.',
    productCount: 35
  },
  {
    id: 'b-3',
    name: 'GIMA S.p.A',
    slug: 'gima-spa',
    description: 'Italian manufacturer of high quality emergency medical devices, first aid, and diagnostic tools.',
    productCount: 42
  },
  {
    id: 'b-4',
    name: 'Nihon Kohden',
    slug: 'nihon-kohden',
    description: 'Pioneering Japanese healthcare technologies in telemetry, patient monitors, and neurology.',
    productCount: 22
  },
  {
    id: 'b-5',
    name: 'GE HealthCare',
    slug: 'ge-healthcare',
    description: 'Innovative medical technology and digital solutions for precision patient care.',
    productCount: 19
  },
  {
    id: 'b-6',
    name: 'Schiller',
    slug: 'schiller',
    description: 'Swiss precision leader in cardiopulmonary diagnostics, defibrillation, and spirometry.',
    productCount: 14
  },
  {
    id: 'b-7',
    name: 'Dräger',
    slug: 'drager',
    description: 'International leader in medical and safety technology, operating room solutions, and anesthesia.',
    productCount: 16
  }
];

export const initialProducts: Product[] = [
  {
    id: 'fom-bs-1',
    name: 'Haier Biomedical HYC-309 Pharmacy Refrigerator 2–8°C, 309 L',
    slug: 'haier-biomedical-hyc-309-pharmacy-refrigerator',
    sku: 'HYC-309',
    productType: 'simple',
    purchaseMode: 'cart',
    regularPrice: 12500,
    salePrice: 10950,
    category: 'Laboratory Equipment',
    brand: 'Haier Biomedical',
    shortDescription: 'Pharmacy and vaccine refrigerator engineered for precise temperature uniformity between 2°C and 8°C with digital display and alarm systems.',
    fullDescription: 'Haier Biomedical HYC-309 Pharmacy Refrigerator delivers superior cooling reliability for pharmaceutical products, vaccines, biologicals, and temperature-sensitive clinical materials. Equipped with forced-air cooling, self-closing glass door, and multi-alarm safety mechanisms.',
    mainImage: '/images/original/Fridges-Pharmacy_Haier_HYC-309.png',
    galleryImages: ['/images/original/Fridges-Pharmacy_Haier_HYC-309.png'],
    stockQuantity: 8,
    lowStockThreshold: 2,
    stockStatus: 'in_stock',
    technicalSpecs: { 'Capacity': '309 Liters', 'Temp Range': '2°C to 8°C', 'Refrigerant': 'Hydrocarbon Eco-friendly', 'Doors': 'Heated glass, self-closing' },
    features: ['Microprocessor temperature control', 'Audible & visual safety alarms', 'Uniform airflow design', 'Clinical Grade Cold-Chain'],
    applications: ['Hospital Pharmacies', 'Vaccination Centers', 'Laboratories', 'Clinics'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    status: "published",
    documents: [],
    tags: ["Medical Equipment", "UAE"],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-24T00:00:00Z'
  },
  {
    id: 'fom-bs-2',
    name: 'Cederroth Sterile Net Wound Dressing | 1893',
    slug: 'cederroth-sterile-net-wound-dressing-1893',
    sku: 'CED-1893',
    productType: 'simple',
    purchaseMode: 'cart',
    regularPrice: 185,
    salePrice: 165,
    category: 'Consumables & Disposables',
    brand: 'Cederroth',
    shortDescription: 'Sterile non-adherent net wound dressing for direct application over acute cuts, burns, and abrasions.',
    fullDescription: 'Cederroth 1893 Sterile Net Wound Dressing allows exudate to pass through freely into an absorbent secondary pad while preventing dressing sticking to fragile new tissue.',
    mainImage: '/images/original/Net-dressing-CEDERROTH-1893-362x500.jpg',
    galleryImages: ['/images/original/Net-dressing2-CEDERROTH-1893-500x500.jpg'],
    stockQuantity: 120,
    lowStockThreshold: 20,
    stockStatus: 'in_stock',
    technicalSpecs: { 'Box Count': '10 pieces/box', 'Sterilization': 'Gamma irradiated', 'Texture': 'Non-adherent porous net' },
    features: ['Non-stick contact layer', 'Painless dressing change', 'Hospital grade sterility'],
    applications: ['Emergency Rooms', 'Ambulatory Care', 'First Aid Stations'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    status: "published",
    documents: [],
    tags: ["Medical Equipment", "UAE"],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-24T00:00:00Z'
  },
  {
    id: 'fom-bs-3',
    name: 'Cederroth Burn Gel Dressing 10 × 10 cm | 901900',
    slug: 'cederroth-burn-gel-dressing-10x10-cm-901900',
    sku: 'CED-901900',
    productType: 'simple',
    purchaseMode: 'cart',
    regularPrice: 95,
    salePrice: 85,
    category: 'Consumables & Disposables',
    brand: 'Cederroth',
    shortDescription: 'Rapid cooling burn gel dressing for 1st and 2nd-degree burns, scalds, and sunburns.',
    fullDescription: 'Provides immediate cooling pain relief, prevents burn progression into deeper tissue layers, and protects against contamination without adhering to damaged skin.',
    mainImage: '/images/original/Burn-Gel-Dressing-10_C3_9710-cm-500x500.jpg',
    galleryImages: ['/images/original/Burn-Gel-Dressing-10_C3_9710-cm1-500x500.jpg'],
    stockQuantity: 95,
    lowStockThreshold: 15,
    stockStatus: 'in_stock',
    technicalSpecs: { 'Size': '10 x 10 cm', 'Gel Base': 'Water-based cooling gel', 'Packaging': 'Individually foil sealed' },
    features: ['Immediate pain reduction', 'Prevents infection', 'Non-toxic, safe for facial application'],
    applications: ['Kitchens & Industry', 'Urgent Care Centers', 'First Aid Kits'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    status: "published",
    documents: [],
    tags: ["Medical Equipment", "UAE"],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-24T00:00:00Z'
  },
  {
    id: 'fom-bs-4',
    name: 'Cederroth Emergency Blanket | 1892',
    slug: 'cederroth-emergency-blanket-1892',
    sku: 'CED-1892',
    productType: 'simple',
    purchaseMode: 'cart',
    regularPrice: 45,
    salePrice: 38,
    category: 'Consumables & Disposables',
    brand: 'Cederroth',
    shortDescription: 'Reflective emergency thermal blanket to prevent hypothermia and shock in trauma patients.',
    fullDescription: 'Dual-surface aluminized emergency rescue foil blanket. Reflects up to 90% of body heat back to patient. Compact, lightweight, water and windproof.',
    mainImage: '/images/original/Emergency-blanket-Cederroth.jpg',
    galleryImages: ['/images/original/Emergency-blanket-Cederroth1.jpg'],
    stockQuantity: 240,
    lowStockThreshold: 30,
    stockStatus: 'in_stock',
    technicalSpecs: { 'Dimensions': '150 x 210 cm', 'Material': 'Aluminized Mylar', 'Weight': '60g' },
    features: ['90% thermal reflection', 'Waterproof & windproof', 'Ultra-compact fold'],
    applications: ['Ambulances', 'Field Operations', 'Disaster Relief'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    status: "published",
    documents: [],
    tags: ["Medical Equipment", "UAE"],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-24T00:00:00Z'
  },
  {
    id: 'fom-bs-5',
    name: 'Blue Dot Reusable Hot & Cold Pack | 30REUHC1',
    slug: 'blue-dot-reusable-hot-cold-pack-30reuhc1',
    sku: 'BD-30REUHC1',
    productType: 'simple',
    purchaseMode: 'cart',
    regularPrice: 35,
    salePrice: 28,
    category: 'Physiotherapy',
    brand: 'Blue Dot',
    shortDescription: 'Flexible dual-purpose gel compress for soothing therapeutic hot or cold pain management.',
    fullDescription: 'Non-toxic therapeutic gel pack that remains flexible at freezing temperatures. Can be microwave heated for muscular aches or freezer chilled for acute sprains and swelling reduction.',
    mainImage: '/images/original/30REUHC1-_E2_80_93-REUSABLE-COLD-HOT-PACK-500x500.jpg',
    galleryImages: ['/images/original/30REUHC1-_E2_80_93-REUSABLE-COLD-HOT-PACK-500x500.jpg'],
    stockQuantity: 180,
    lowStockThreshold: 25,
    stockStatus: 'in_stock',
    technicalSpecs: { 'Type': 'Reusable thermal gel', 'Size': 'Standard anatomical 13 x 28 cm', 'Safety': 'Non-toxic gel formula' },
    features: ['Microwave & freezer safe', 'Flexible when frozen', 'Durable puncture-resistant exterior'],
    applications: ['Physiotherapy Clinics', 'Sports Medicine', 'Post-Op Recovery'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    status: "published",
    documents: [],
    tags: ["Medical Equipment", "UAE"],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-24T00:00:00Z'
  },
  {
    id: 'fom-bs-6',
    name: 'Haier Biomedical HYC-410 Pharmacy Refrigerator – 410L, 2–8°C',
    slug: 'haier-biomedical-hyc-410-pharmacy-refrigerator',
    sku: 'HYC-410',
    productType: 'simple',
    purchaseMode: 'cart',
    regularPrice: 15800,
    salePrice: 14200,
    category: 'Laboratory Equipment',
    brand: 'Haier Biomedical',
    shortDescription: 'Large 410-liter clinical pharmacy refrigerator with multi-layer adjustable shelving and continuous temperature monitoring.',
    fullDescription: 'High-capacity medical refrigerator engineered for large hospitals and centralized pharmaceutical storage. Features USB data download for GMP compliance and smart forced air circulation.',
    mainImage: '/images/original/1200Wx1200H-HYC-410-USBCURB-HYC-410-USBCURB-1-20250627-500x500.jpg',
    galleryImages: ['/images/original/1200Wx1200H-HYC-410-USBCURB-HYC-410-USBCURB-1-20250627-500x500.jpg'],
    stockQuantity: 5,
    lowStockThreshold: 1,
    stockStatus: 'in_stock',
    technicalSpecs: { 'Capacity': '410 Liters', 'Shelves': '5 adjustable wire shelves', 'Display': 'LED digital display', 'Interface': 'USB data download' },
    features: ['High-accuracy ±1°C sensor control', 'Keyed lock for controlled pharmaceuticals', 'Auto-defrost system'],
    applications: ['Central Hospitals', 'Blood Banks', 'Pharmaceutical Warehouses'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    status: "published",
    documents: [],
    tags: ["Medical Equipment", "UAE"],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-24T00:00:00Z'
  },
  {
    id: 'fom-bs-7',
    name: 'Blue Dot Easy Ice Instant Ice Pack | 9987',
    slug: 'blue-dot-easy-ice-instant-ice-pack-9987',
    sku: 'BD-9987',
    productType: 'simple',
    purchaseMode: 'cart',
    regularPrice: 25,
    salePrice: 18,
    category: 'Consumables & Disposables',
    brand: 'Blue Dot',
    shortDescription: 'Single-use chemical activation instant cold pack without prior refrigeration needed.',
    fullDescription: 'Squeeze to activate instant cold pack. Reaches therapeutic cold within 3 seconds, ideal for immediate field treatment of acute sprains, bruises, and contusions.',
    mainImage: '/images/original/Blue-Dot-Easy-Ice-Instant-Ice-Pack-9987.webp',
    galleryImages: ['/images/original/Blue-Dot-Easy-Ice-Instant-Ice-Pack-9987.webp'],
    stockQuantity: 310,
    lowStockThreshold: 50,
    stockStatus: 'in_stock',
    technicalSpecs: { 'Activation': 'Internal water pouch burst', 'Duration': '20-30 minutes therapeutic cold', 'Packaging': 'Single pack' },
    features: ['No freezer required', 'Instant activation', 'Essential emergency supply'],
    applications: ['Schools & Sports Clubs', 'Construction Sites', 'Ambulances'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    status: "published",
    documents: [],
    tags: ["Medical Equipment", "UAE"],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-24T00:00:00Z'
  },
  {
    id: 'fom-bs-8',
    name: 'Blue Dot Heavy Duty Medium Clinical Waste Bags',
    slug: 'blue-dot-heavy-duty-medium-clinical-waste-bags',
    sku: 'BD-CLIN-BAG',
    productType: 'simple',
    purchaseMode: 'cart',
    regularPrice: 120,
    salePrice: 95,
    category: 'Consumables & Disposables',
    brand: 'Blue Dot',
    shortDescription: 'Certified UN-approved yellow biohazard clinical waste disposal bags with star-seal bottom.',
    fullDescription: 'High-density puncture and tear resistant clinical waste bags compliant with UAE environmental and healthcare waste segregation standards. Pack of 50 heavy-duty liners.',
    mainImage: '/images/original/Heavy-Duty-Medium-Clinical-Waste-Bags-500x500.webp',
    galleryImages: ['/images/original/Heavy-Duty-Medium-Clinical-Waste-Bags-500x500.webp'],
    stockQuantity: 150,
    lowStockThreshold: 20,
    stockStatus: 'in_stock',
    technicalSpecs: { 'Color': 'Biohazard Yellow with black print', 'Capacity': '50 Liters', 'Pack Size': 'Roll of 50 bags' },
    features: ['Puncture-resistant high gauge film', 'Leak-proof star seal bottom', 'UN certified biohazard symbol'],
    applications: ['Dental Clinics', 'Laboratories', 'Hospital Wards'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    status: "published",
    documents: [],
    tags: ["Medical Equipment", "UAE"],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-24T00:00:00Z'
  },
  {
    id: 'fom-bs-9',
    name: 'Blue Dot Revive Aid Resuscitation Device | 30REVA01',
    slug: 'blue-dot-revive-aid-resuscitation-device-30reva01',
    sku: 'BD-30REVA01',
    productType: 'simple',
    purchaseMode: 'cart',
    regularPrice: 55,
    salePrice: 45,
    category: 'General Medical Devices',
    brand: 'Blue Dot',
    shortDescription: 'CPR resuscitation face shield with one-way non-rebreathing valve for hygienic rescue ventilation.',
    fullDescription: 'Provides sanitary barrier protection between rescuer and patient during mouth-to-mouth resuscitation. Includes high-efficiency one-way valve with 3M bacterial filter.',
    mainImage: '/images/original/REVIVE-AID-RESUSCITATION-DEVICE-500x500.webp',
    galleryImages: ['/images/original/REVIVE-AID-RESUSCITATION-DEVICE1-500x500.webp'],
    stockQuantity: 85,
    lowStockThreshold: 15,
    stockStatus: 'in_stock',
    technicalSpecs: { 'Valve': 'One-way non-rebreathing valve', 'Filter': 'Bacterial filter membrane', 'Case': 'Compact plastic carry case' },
    features: ['Zero cross-contamination risk', 'Clear transparent mask', 'Fits adults and children'],
    applications: ['First Responders', 'Lifeguards', 'Paramedic Kits'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    status: "published",
    documents: [],
    tags: ["Medical Equipment", "UAE"],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-24T00:00:00Z'
  },
  {
    id: 'fom-bs-10',
    name: 'Salvequick Waterproof Plaster Strips Refill | 6036',
    slug: 'salvequick-waterproof-plaster-strips-refill-6036',
    sku: 'SALV-6036',
    productType: 'simple',
    purchaseMode: 'cart',
    regularPrice: 42,
    salePrice: 35,
    category: 'Consumables & Disposables',
    brand: 'Salvequick',
    shortDescription: 'Sterile waterproof adhesive wound plaster refill pack for clinical dispensers.',
    fullDescription: 'Salvequick 6036 refill pack contains breathable, sterile waterproof plasters that remain securely affixed during washing and clinical hand hygiene routines.',
    mainImage: '/images/original/Salvequick-Plaster-Strips-Waterproof-500x500.webp',
    galleryImages: ['/images/original/Salvequick-Plaster-Strips-Waterproof-500x500.webp'],
    stockQuantity: 140,
    lowStockThreshold: 20,
    stockStatus: 'in_stock',
    technicalSpecs: { 'Pack Contents': '45 assorted waterproof plasters', 'Adhesive': 'Hypoallergenic polyacrylate' },
    features: ['100% waterproof seal', 'Dispensers refill compatible', 'Gentle on sensitive skin'],
    applications: ['Clinic Stations', 'Laboratories', 'Surgery Suites'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    status: "published",
    documents: [],
    tags: ["Medical Equipment", "UAE"],
    createdAt: '2026-09-01T00:00:00Z',
    updatedAt: '2026-09-24T00:00:00Z'
  }
,
  {
    id: 'prod-fom-001',
    name: 'Haier Biomedical HYC-309 Pharmacy Refrigerator 2–8°C, 309 L',
    slug: 'haier-biomedical-hyc-309-pharmacy-refrigerator-2-8c-309-l',
    sku: 'HYC-309-UAE',
    productType: 'simple',
    purchaseMode: 'cart',
    regularPrice: 6199,
    salePrice: 5999,
    category: 'Pharmacy Refrigerators',
    brand: 'Haier Biomedical',
    model: 'HYC-309',
    shortDescription: 'Haier Biomedical HYC-309 Pharmacy Refrigerator is a temperature-controlled medical refrigerator designed for storing biological drugs and other temperature-sensitive items at 2–8°C in UAE pharmacies and hospitals.',
    fullDescription: `The Haier Biomedical HYC-309 Pharmacy Refrigerator is a professional, high-reliability cold storage unit engineered specifically for healthcare institutions, pharmacies, diagnostic laboratories, and pharmaceutical companies in the UAE.

### Key Highlights:
- **Temperature Precision:** Microprocessor temperature control system with digital display maintains interior temperature between +2°C and +8°C with ±0.1°C resolution.
- **Forced Air Circulation:** Multi-duct vortex circulation system guarantees uniform temperature distribution across all adjustable shelves.
- **Audible & Visual Alarms:** High/low temperature alarms, power failure alarm, door ajar alarm, and sensor error notification protect valuable biological products.
- **Heated Glass Door:** Multi-layer heated glass prevents condensation even under high UAE ambient humidity conditions.
- **Eco-Friendly Refrigerant:** Hydrocarbon (HC) refrigeration system cuts energy consumption while exceeding international environmental benchmarks.`,
    mainImage: 'https://www.fastonmed.com/wp-content/uploads/2026/09/Fridges-Pharmacy_Haier_HYC-309.png',
    galleryImages: [
      'https://www.fastonmed.com/wp-content/uploads/2026/09/Fridges-Pharmacy_Haier_HYC-309.png',
      'https://www.fastonmed.com/wp-content/uploads/2025/06/accessories-1.jpeg'
    ],
    stockQuantity: 12,
    lowStockThreshold: 3,
    stockStatus: 'in_stock',
    warrantyPeriod: '3 Years Warranty on Compressor, 1 Year Comprehensive',
    technicalSpecs: {
      'Storage Capacity': '309 Litres',
      'Temperature Range': '2°C to 8°C',
      'Refrigerant': 'R600a (Eco-Friendly HC)',
      'Dimensions (W x D x H)': '645 × 690 × 1810 mm',
      'Internal Shelves': '5 Adjustable Plastic-Coated Wire Shelves',
      'Power Supply': '220V - 240V / 50Hz (UAE Standard)',
      'Locking System': 'Cylinder Safety Lock with Keys',
      'Data Logging': 'USB Interface for Automated Temperature Log Export'
    },
    features: [
      'High-accuracy microprocessor controller with LED digital readout',
      'Forced air vortex circulation with DC turbo fan',
      'Electric heated double-pane glass door eliminating misting',
      'Built-in USB temperature recording and remote alarm contacts',
      'Whisper-quiet operational noise level (<40 dB)'
    ],
    applications: [
      'Hospital central pharmacies & pharmacy chains',
      'Clinical vaccine storage & immunisation clinics',
      'Biopharmaceutical research laboratories',
      'Private clinic medication rooms'
    ],
    documents: [
      { title: 'Haier HYC-309 User Manual (PDF)', url: '#', size: '2.4 MB' },
      { title: 'CE & MoH Compliance Certificate', url: '#', size: '850 KB' }
    ],
    tags: ['Pharmacy Refrigerator', 'Medical Cold Storage', 'Haier Biomedical', '2-8C Refrigerator', 'UAE Stock'],
    isFeatured: true,
    isBestSeller: true,
    isNew: false,
    status: 'published',
    seoTitle: 'Haier Biomedical HYC-309 Pharmacy Refrigerator 2–8°C 309L UAE',
    seoDescription: 'Buy Haier Biomedical HYC-309 Pharmacy Refrigerator in UAE. 309 L capacity, 2-8°C precise cooling, heated glass door, USB data logging. Fast delivery across Dubai and Abu Dhabi.',
    rating: 5,
    reviewCount: 14,
    createdAt: '2026-09-01T10:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z'
  },
  {
    id: 'prod-fom-002',
    name: 'Mindray SV-300 Turbine-Based ICU Ventilator',
    slug: 'mindray-sv-300-icu-ventilator',
    sku: 'MND-SV300-PRO',
    productType: 'simple',
    purchaseMode: 'quote',
    regularPrice: 48000,
    salePrice: 45000,
    category: 'ICU Equipment',
    brand: 'Mindray',
    model: 'SV-300',
    shortDescription: 'State-of-the-art turbine-driven ICU ventilator equipped with high-level invasive and non-invasive ventilation modes for pediatric and adult critical patients.',
    fullDescription: `The Mindray SV-300 is a compact yet exceptionally powerful mechanical ventilator designed for adult and pediatric patients in intensive care units, emergency departments, and intra-hospital transport.

Its integrated turbine does not rely on a central compressed air supply, making it versatile for field hospitals and flexible ICU bed reallocations across UAE healthcare facilities.

### Clinical Capabilities:
- Comprehensive modes: V-A/C, P-A/C, V-SIMV, P-SIMV, CPAP/PSV, DuoLevel, PRVC, and Non-Invasive Ventilation (NIV).
- Integrated SpO2 and Volumetric CO2 monitoring.
- High Flow Oxygen Therapy (HFNC) mode for respiratory support.
- 12.2" high-resolution tiltable capacitive touchscreen with intuitive user layout.`,
    mainImage: 'https://www.fastonmed.com/wp-content/uploads/2025/06/genaral-equipments-1.jpeg',
    galleryImages: [
      'https://www.fastonmed.com/wp-content/uploads/2025/06/genaral-equipments-1.jpeg'
    ],
    stockQuantity: 5,
    lowStockThreshold: 2,
    stockStatus: 'in_stock',
    warrantyPeriod: '2 Years Manufacturer Warranty + Annual Preventive Maintenance',
    technicalSpecs: {
      'Ventilation Type': 'Turbine Driven (No central air required)',
      'Tidal Volume': '20 to 2000 mL',
      'Display': '12.2-inch Color TFT Touchscreen',
      'Battery Backup': 'Up to 6 Hours with Dual Li-Ion Batteries',
      'Patient Weight Range': 'Pediatric (>= 3kg) to Adult',
      'High Flow Therapy': '2 to 60 L/min'
    },
    features: [
      'Independent turbine drive with whisper-quiet operation',
      'Automatic tube compensation (ATRC) and weaning indicators',
      'Integrated pneumatic nebulizer connector',
      'Detachable and autoclavable exhalation valve'
    ],
    applications: ['ICU', 'Post-Anesthesia Care (PACU)', 'Emergency Triage', 'Sub-Acute Respiratory Units'],
    documents: [
      { title: 'Mindray SV-300 Clinical Brochure', url: '#', size: '4.1 MB' }
    ],
    tags: ['ICU Ventilator', 'Mindray', 'Critical Care', 'Turbine Ventilator'],
    isFeatured: true,
    isBestSeller: true,
    isNew: true,
    status: 'published',
    seoTitle: 'Mindray SV-300 ICU Ventilator UAE - Price & Specifications',
    seoDescription: 'Request quote for Mindray SV-300 turbine-based ICU ventilator in UAE. MoH approved, pediatric and adult ventilation modes, full training and warranty included.',
    rating: 5,
    reviewCount: 8,
    createdAt: '2026-09-02T10:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z'
  },
  {
    id: 'prod-fom-003',
    name: 'Nihon Kohden Life Scope G3 Multi-Parameter Patient Monitor',
    slug: 'nihon-kohden-life-scope-g3-patient-monitor',
    sku: 'NK-LS-G3',
    productType: 'simple',
    purchaseMode: 'quote',
    regularPrice: 14500,
    salePrice: 13200,
    category: 'Patient Monitoring',
    brand: 'Nihon Kohden',
    model: 'Life Scope G3',
    shortDescription: 'High-acuity bedside patient monitor offering continuous ECG arrhythmia detection, high-accuracy NIBP (iNIBP), and pulse oximetry.',
    fullDescription: `The Nihon Kohden Life Scope G3 patient monitor delivers dependable clinical accuracy for UAE operating rooms, recovery suites, and emergency rooms. Equipped with Nihon Kohden's proprietary algorithms, it significantly minimizes false alarms while delivering crisp physiological waveforms.`,
    mainImage: 'https://www.fastonmed.com/wp-content/uploads/2025/06/genaral-equipments-1.jpeg',
    galleryImages: ['https://www.fastonmed.com/wp-content/uploads/2025/06/genaral-equipments-1.jpeg'],
    stockQuantity: 15,
    lowStockThreshold: 4,
    stockStatus: 'in_stock',
    warrantyPeriod: '2 Years Comprehensive Warranty',
    technicalSpecs: {
      'Screen Size': '15.6-inch Touchscreen Color LCD',
      'Standard Parameters': 'ECG (3/5/10 Lead), SpO2, NIBP, Respiration, 2x Temp',
      'Optional Modules': 'EtCO2, Dual IBP, Cardiac Output, BIS',
      'Waveforms Displayed': 'Up to 12 simultaneous waveforms'
    },
    features: [
      'Smart Cable system that detects transducer types automatically',
      'ec1 arrhythmia analysis with high sensitivity',
      'High-speed network interface for central monitoring integration'
    ],
    applications: ['Operating Rooms', 'ICU / CCU', 'Day Surgery Recovery'],
    documents: [{ title: 'Life Scope G3 Technical Specifications', url: '#', size: '1.8 MB' }],
    tags: ['Patient Monitor', 'Nihon Kohden', 'Bedside Monitor', 'ECG Monitor'],
    isFeatured: true,
    isBestSeller: false,
    isNew: false,
    status: 'published',
    seoTitle: 'Nihon Kohden Life Scope G3 Patient Monitor UAE',
    seoDescription: 'Nihon Kohden patient monitoring solutions for hospitals in Dubai and Abu Dhabi. Request quote from FastonMed authorized supplier.',
    rating: 5,
    reviewCount: 6,
    createdAt: '2026-09-03T10:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z'
  },
  {
    id: 'prod-fom-004',
    name: 'GIMA First Aid Air Cushion Splints – Set of 4 Pieces | 34106',
    slug: 'gima-first-aid-air-cushion-splints-set-of-4-pieces-34106',
    sku: 'GIMA-34106',
    productType: 'simple',
    purchaseMode: 'cart',
    regularPrice: 420,
    salePrice: 380,
    category: 'Consumables & Disposables',
    brand: 'GIMA S.p.A',
    model: '34106',
    shortDescription: 'Reusable first-aid pneumatic immobilization splint set with inflating pump and 4-compartment carry bag for emergency patient stabilization.',
    fullDescription: `The GIMA First Aid Air Cushion Splint Set (Ref: 34106) provides fast, practical limb immobilization following vehicular accidents, fractures, sprains, or traumatic crush injuries.

Constructed from transparent, heavy-duty medical grade PVC, the splints permit continuous visual skin assessment without needing to deflate or remove the device. Furthermore, they are 100% radiolucent, enabling direct emergency X-ray diagnostic imaging.`,
    mainImage: 'https://www.fastonmed.com/wp-content/uploads/2026/09/FIRST-AID-AIR-CUSHION-SPLINTS-set-of-4-pcs.jpg',
    galleryImages: ['https://www.fastonmed.com/wp-content/uploads/2026/09/FIRST-AID-AIR-CUSHION-SPLINTS-set-of-4-pcs.jpg'],
    stockQuantity: 45,
    lowStockThreshold: 10,
    stockStatus: 'in_stock',
    warrantyPeriod: '1 Year Standard Warranty',
    technicalSpecs: {
      'Material': 'High-Durability Transparent Medical PVC',
      'Included Splints': 'Full Leg, Foot/Ankle, Full Arm, Hand/Wrist',
      'X-Ray Transparency': '100% Radiolucent (X-ray safe)',
      'Pump': 'Manual Dual-Action Inflation Pump Included'
    },
    features: [
      'Instant pressure relief valve preventing limb over-inflation',
      'Visual injury monitoring through transparent chambers',
      'Washable and disinfectant resistant for clinical reusability'
    ],
    applications: ['Ambulance / EMS Paramedic Units', 'Emergency Trauma Rooms', 'Sports Arenas & Industrial First Aid'],
    documents: [{ title: 'GIMA 34106 Splint Usage Protocol', url: '#', size: '650 KB' }],
    tags: ['First Aid Splints', 'Emergency Equipment', 'GIMA', 'Radiolucent Splint'],
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    status: 'published',
    seoTitle: 'GIMA First Aid Air Cushion Splints Set of 4 UAE - Buy Online',
    seoDescription: 'Order GIMA 34106 emergency air cushion splint set in UAE. Includes pump and case. In stock with same-day Dubai dispatch.',
    rating: 5,
    reviewCount: 19,
    createdAt: '2026-09-04T10:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z'
  },
  {
    id: 'prod-fom-005',
    name: 'Belmont Clesta II Advanced Dental Treatment Unit & Chair',
    slug: 'belmont-clesta-ii-dental-treatment-unit',
    sku: 'BLM-CLESTA2',
    productType: 'simple',
    purchaseMode: 'quote',
    regularPrice: 58000,
    salePrice: 52000,
    category: 'Dental Equipment',
    brand: 'Belmont',
    model: 'Clesta II',
    shortDescription: 'Japanese engineered electro-hydraulic dental delivery workstation providing supreme ergonomic comfort, smooth motion, and seamless hygiene disinfection.',
    fullDescription: `The Belmont Clesta II represents decades of Japanese engineering excellence in dental equipment. Designed to meet the demanding pace of modern UAE dental practices, it pairs twin-axis articulated headrests with silent electro-hydraulic positioning.`,
    mainImage: 'https://www.fastonmed.com/wp-content/uploads/2025/06/dental-chair-1.jpeg',
    galleryImages: ['https://www.fastonmed.com/wp-content/uploads/2025/06/dental-chair-1.jpeg'],
    stockQuantity: 4,
    lowStockThreshold: 1,
    stockStatus: 'in_stock',
    warrantyPeriod: '3 Years Warranty on Hydraulic System, 1 Year Parts',
    technicalSpecs: {
      'Operation System': 'Twin-Axis Electro-Hydraulic Mechanism',
      'Spittoon': 'Porcelain Cuspidor with Auto-Flush & Cup Filler',
      'Operating Light': 'LED Dental Shadowless Lamp with Sensor Dimming',
      'Doctor Table': 'Over-Patient Continental or Under-Delivery System'
    },
    features: [
      'Ultra-quiet hydraulic motor with soft stop technology',
      'Seamless seamless upholstery resistant to medical sanitizers',
      'Foot control pedal with preset memory programs'
    ],
    applications: ['Private Dental Clinics', 'Maxillofacial Dental Centers', 'Dental University Teaching Hospitals'],
    documents: [{ title: 'Belmont Clesta II Installation Guide', url: '#', size: '5.2 MB' }],
    tags: ['Dental Chair', 'Belmont', 'Dental Delivery System', 'Clinic Equipment'],
    isFeatured: true,
    isBestSeller: false,
    isNew: false,
    status: 'published',
    seoTitle: 'Belmont Clesta II Dental Chair UAE Supplier - FastonMed',
    seoDescription: 'Inquire on Belmont Clesta II Japanese dental treatment chair in UAE. Complete installation, warranty, and technician support across Dubai and Abu Dhabi.',
    rating: 5,
    reviewCount: 5,
    createdAt: '2026-09-05T10:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z'
  },
  {
    id: 'prod-fom-006',
    name: 'Medical Nitrile Examination Gloves (Powder-Free, Box of 100)',
    slug: 'medical-nitrile-examination-gloves-box-of-100',
    sku: 'GLV-NIT-100',
    productType: 'variable',
    purchaseMode: 'cart',
    regularPrice: 28,
    salePrice: 24,
    category: 'Consumables & Disposables',
    brand: 'GIMA S.p.A',
    shortDescription: 'Latex-free, powder-free medical exam nitrile gloves offering superior tactile sensitivity and chemical splash resistance. Available in Small, Medium, Large, XL.',
    fullDescription: `Premium medical grade nitrile examination gloves formulated without natural rubber latex proteins to eliminate Type I allergy concerns. Textured fingertips ensure superior wet and dry grip when handling delicate surgical instruments or diagnostic reagents.`,
    mainImage: 'https://www.fastonmed.com/wp-content/uploads/2025/06/consumables-1.jpeg',
    galleryImages: ['https://www.fastonmed.com/wp-content/uploads/2025/06/consumables-1.jpeg'],
    stockQuantity: 450,
    lowStockThreshold: 50,
    stockStatus: 'in_stock',
    warrantyPeriod: 'Shelf Life 3 Years',
    technicalSpecs: {
      'Material': '100% Acrylonitrile Butadiene (Nitrile)',
      'Packaging': '100 Gloves per Dispenser Box (10 Boxes per Carton)',
      'Certifications': 'EN 455 Parts 1-4, ASTM D6319, CE Marked',
      'Thickness': '3.5 mil Fingertip, 3.0 mil Palm'
    },
    features: [
      'Powder-free polymer coating for effortless donning',
      'Micro-textured fingertips for precision tactile control',
      'Resistant to a wide spectrum of hospital chemicals & chemotherapy drugs'
    ],
    applications: ['Hospitals', 'Dental Clinics', 'Pathology Laboratories', 'General Practitioners'],
    documents: [{ title: 'EN 455 Compliance Certificate', url: '#', size: '420 KB' }],
    tags: ['Nitrile Gloves', 'Medical Gloves', 'Consumables', 'PPE UAE'],
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    status: 'published',
    variations: [
      { id: 'var-glv-s', sku: 'GLV-NIT-S', regularPrice: 28, salePrice: 24, stockQuantity: 120, stockStatus: 'in_stock', attributes: { Size: 'Small' } },
      { id: 'var-glv-m', sku: 'GLV-NIT-M', regularPrice: 28, salePrice: 24, stockQuantity: 180, stockStatus: 'in_stock', attributes: { Size: 'Medium' } },
      { id: 'var-glv-l', sku: 'GLV-NIT-L', regularPrice: 28, salePrice: 24, stockQuantity: 100, stockStatus: 'in_stock', attributes: { Size: 'Large' } },
      { id: 'var-glv-xl', sku: 'GLV-NIT-XL', regularPrice: 30, salePrice: 26, stockQuantity: 50, stockStatus: 'in_stock', attributes: { Size: 'X-Large' } }
    ],
    seoTitle: 'Medical Nitrile Examination Gloves Powder-Free UAE - FastonMed',
    seoDescription: 'Buy medical nitrile gloves in Dubai, UAE. Powder-free, latex-free boxes of 100. Small, Medium, Large, XL sizes with fast UAE bulk delivery.',
    rating: 5,
    reviewCount: 32,
    createdAt: '2026-09-06T10:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z'
  },
  {
    id: 'prod-fom-007',
    name: 'Schiller Cardiovit FT-1 Ultra-Portable Touchscreen ECG Machine',
    slug: 'schiller-cardiovit-ft-1-touchscreen-ecg-machine',
    sku: 'SCH-FT1-ECG',
    productType: 'simple',
    purchaseMode: 'quote',
    regularPrice: 11500,
    salePrice: 10800,
    category: 'Patient Monitoring',
    brand: 'Schiller',
    model: 'Cardiovit FT-1',
    shortDescription: 'Compact tablet-format 12-lead diagnostic electrocardiograph equipped with Swiss ETM interpretation software and Wi-Fi EMR transmission.',
    fullDescription: `The Schiller Cardiovit FT-1 is an ultra-portable 12-lead diagnostic ECG designed for medical practitioners who value maximum mobility without compromising on Swiss precision signal processing. Weighing just over one kilogram, it integrates a multi-touch capacitive screen and built-in thermal printer.`,
    mainImage: 'https://www.fastonmed.com/wp-content/uploads/2025/06/genaral-equipments-1.jpeg',
    galleryImages: ['https://www.fastonmed.com/wp-content/uploads/2025/06/genaral-equipments-1.jpeg'],
    stockQuantity: 9,
    lowStockThreshold: 2,
    stockStatus: 'in_stock',
    warrantyPeriod: '2 Years Manufacturer Warranty',
    technicalSpecs: {
      'Leads': '12 Simultaneous Diagnostic Leads',
      'Display': '8-inch High Resolution Multi-Touch Screen',
      'Connectivity': 'Built-in Wi-Fi & USB (DICOM/HL7 compatible)',
      'Printer': 'Internal Thermal Z-Fold Printer'
    },
    features: [
      'Famous Schiller ETM interpretation algorithm for adult & pediatric patients',
      'Rapid touch navigation with intuitive on-screen keyboard',
      'Direct PDF export to hospital network shares via Wi-Fi'
    ],
    applications: ['Cardiology Clinics', 'Emergency Triage', 'Ambulance EMS', 'Home Healthcare Doctors'],
    documents: [{ title: 'Cardiovit FT-1 Technical Brochure', url: '#', size: '2.1 MB' }],
    tags: ['ECG Machine', 'Schiller', '12-Lead ECG', 'Diagnostic ECG'],
    isFeatured: true,
    isBestSeller: false,
    isNew: true,
    status: 'published',
    seoTitle: 'Schiller Cardiovit FT-1 Portable ECG Machine UAE',
    seoDescription: 'Schiller Cardiovit FT-1 12-lead touch ECG machine supplier in UAE. Wi-Fi EMR integration, Swiss ETM software, in stock at FastonMed.',
    rating: 5,
    reviewCount: 7,
    createdAt: '2026-09-07T10:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z'
  },
  {
    id: 'prod-fom-008',
    name: 'Reusable SpO2 Adult Finger Clip Sensor for Mindray / Nihon Kohden',
    slug: 'reusable-spo2-adult-finger-clip-sensor',
    sku: 'ACC-SPO2-ADULT',
    productType: 'simple',
    purchaseMode: 'cart',
    regularPrice: 220,
    salePrice: 195,
    category: 'Accessories',
    brand: 'Mindray',
    shortDescription: 'High-durability silicone adult finger clip pulse oximetry sensor with 3-meter shielded cable, compatible with leading patient monitoring systems.',
    fullDescription: `Durable, ergonomically padded pulse oximeter finger sensor engineered for continuous non-invasive oxygen saturation monitoring in adult patients (>40 kg). Shielded low-noise cabling prevents electro-surgical interference in UAE surgical operating environments.`,
    mainImage: 'https://www.fastonmed.com/wp-content/uploads/2025/06/accessories-1.jpeg',
    galleryImages: ['https://www.fastonmed.com/wp-content/uploads/2025/06/accessories-1.jpeg'],
    stockQuantity: 80,
    lowStockThreshold: 15,
    stockStatus: 'in_stock',
    warrantyPeriod: '6 Months Replacement Warranty',
    technicalSpecs: {
      'Patient Weight': 'Adult (>40 kg)',
      'Cable Length': '3.0 Meters (Low-Noise TPU Jacket)',
      'Connector': 'Circular 6-Pin / 7-Pin Gold-Plated Connector',
      'Accuracy': '70%–100% (±2%)'
    },
    features: [
      'Medical-grade biocompatible silicone pads',
      'Gold-plated contacts ensuring noise-free continuous signal',
      'Easy to sanitize with standard isopropyl alcohol wipes'
    ],
    applications: ['ICU', 'OR', 'Post-Op Recovery', 'General Wards'],
    documents: [{ title: 'SpO2 Cable Cleaning & Care Manual', url: '#', size: '320 KB' }],
    tags: ['SpO2 Sensor', 'Pulse Oximeter Cable', 'Patient Monitor Accessories'],
    isFeatured: false,
    isBestSeller: true,
    isNew: false,
    status: 'published',
    seoTitle: 'Reusable SpO2 Adult Finger Sensor Cable UAE - Buy Online',
    seoDescription: 'Fast delivery across Dubai and UAE for Mindray compatible SpO2 adult finger clip cables and patient monitor accessories.',
    rating: 5,
    reviewCount: 23,
    createdAt: '2026-09-08T10:00:00Z',
    updatedAt: '2026-09-24T12:00:00Z'
  }
];

export const initialOrders: Order[] = [];

export const initialCustomers: Customer[] = [];

export const initialEnquiries: Enquiry[] = [];

export const initialCoupons: Coupon[] = [
  {
    id: 'cp-1',
    code: 'WELCOME10',
    description: '10% discount on initial medical consumable purchase',
    discountType: 'percentage',
    discountValue: 10,
    minSpend: 200,
    maxSpend: 2000,
    usageLimit: 100,
    usageCount: 23,
    isActive: true
  },
  {
    id: 'cp-2',
    code: 'UAECARE50',
    description: 'AED 50 off on orders above AED 1,000',
    discountType: 'fixed',
    discountValue: 50,
    minSpend: 1000,
    usageLimit: 50,
    usageCount: 8,
    isActive: true
  }
];

export const initialBlogPosts: BlogPost[] = [
  {
    id: "blog-1",
    title: "How to Choose the Right Pharmacy Refrigerator for UAE Climate Regulations",
    slug: "how-to-choose-the-right-pharmacy-refrigerator-uae",
    excerpt: "Key considerations when selecting temperature-controlled 2-8°C medical refrigerators to comply with UAE clinical cold storage standards.",
    content: "Ensuring vaccine and drug potency in the United Arab Emirates requires specialized commercial-grade pharmacy refrigerators capable of operating seamlessly during extreme summer ambient temperatures exceeding 45°C.\n\n### Why Domestic Fridges Are Prohibited\nDomestic refrigerators suffer from severe internal temperature stratification (+1°C on bottom shelves to +11°C on top door trays) and lack automated thermal data logging. In contrast, specialized medical refrigerators like the Haier Biomedical HYC Series utilize multi-duct vortex forced circulation, maintaining uniform 2–8°C across all corners with ±0.1°C precision.\n\n### Key Compliance Checklist:\n1. Audible & Visual Alarms: Instant alerts for power failure, temperature deviations, and ajar doors.\n2. Heated Anti-Condensation Glass: Prevents moisture accumulation in humid coastal UAE climates.\n3. Automated USB Data Logging: Enables biomedical teams to provide continuous 24/7 audit records during clinical storage inspections.",
    featuredImage: "https://www.fastonmed.com/wp-content/uploads/2026/09/Fridges-Pharmacy_Haier_HYC-309.png",
    category: "Medical Cold Storage",
    tags: ["Healthcare Regulations", "Pharmacy Refrigerator", "Vaccine Storage", "Haier Biomedical"],
    author: "Eng. Tariq Al-Nuaimi",
    authorRole: "Written By",
    authorImage: "https://images.unsplash.com/photo-1622253692010-333f2da6031d?auto=format&fit=crop&w=150&q=80",
    reviewer: "Dr. Laila Al-Zahra, Clinical Director",
    reviewerRole: "Reviewed by:",
    reviewerImage: "https://images.unsplash.com/photo-1594824813511-c918c50e4b77?auto=format&fit=crop&w=150&q=80",
    showByline: true,
    showAuthor: true,
    showReviewer: true,
    views: 1420,
    status: "published",
    publishedAt: "2026-09-15T08:00:00Z",
    seoTitle: "How to Choose a Pharmacy Refrigerator in UAE - Clinical Storage Guide",
    seoDescription: "Comprehensive guide to choosing medical and pharmacy refrigerators in UAE. Learn 2-8°C cold chain requirements, heated glass doors, and medical standards."
  },
  {
    id: "blog-2",
    title: "Essential Medical Equipment for Setting Up a Day Surgery Centre in Dubai",
    slug: "essential-medical-equipment-day-surgery-centre-dubai",
    excerpt: "A comprehensive checklist of high-standard operating room, anesthesia, and recovery equipment needed for outpatient surgery clinics in Dubai.",
    content: "Setting up a Day Surgery Centre in Dubai requires strict adherence to international and UAE medical facility guidelines.\n\nFrom surgical LED shadowless lights and motorized operating tables to multiparameter patient monitors and autoclave sterilizers, having authorized local supplier backing ensures prompt installation, testing, and commissioning.",
    featuredImage: "https://www.fastonmed.com/wp-content/uploads/2025/06/genaral-equipments-1.jpeg",
    category: "Healthcare Facility Setup",
    tags: ["Clinical Guidelines", "Day Surgery Dubai", "Operating Theatre", "Patient Monitors"],
    author: "FastonMed Clinical Advisory",
    authorRole: "Written By",
    authorImage: "https://images.unsplash.com/photo-1559839734-2b71ea197ec2?auto=format&fit=crop&w=150&q=80",
    reviewer: "Biomedical Engineering Board",
    reviewerRole: "Reviewed by:",
    reviewerImage: "",
    showByline: true,
    showAuthor: true,
    showReviewer: false,
    views: 890,
    status: "published",
    publishedAt: "2026-09-10T10:00:00Z",
    seoTitle: "Day Surgery Medical Equipment Checklist Dubai - Clinic Ready",
    seoDescription: "Complete medical equipment guide for setting up Day Surgery Centres in Dubai, UAE. Quality OR tables, ventilators, monitors, and autoclaves."
  },
  {
    id: "blog-3",
    title: "Hospital Autoclave Sterilization Standards: Class B vs Class S autoclaves",
    slug: "hospital-autoclave-sterilization-standards-class-b-vs-s",
    excerpt: "Understand the critical differences between Class B vacuum sterilizers and Class S autoclaves for dental, surgical, and ophthalmic instruments.",
    content: "Class B autoclaves incorporate a fractional pre-vacuum stage that extracts all air pockets from hollow, porous, and cannulated surgical instruments before saturated steam injection.\n\nFor sterile processing departments (CSSD) and surgical suites across Abu Dhabi and Dubai, Class B sterilizers represent the gold standard under EN 13060 European medical standards.",
    featuredImage: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80",
    category: "Sterilization & Infection Control",
    tags: ["Autoclave", "Class B Sterilizer", "CSSD", "Infection Control"],
    author: "Dr. Kareem Mansour",
    authorRole: "Written By",
    authorImage: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?auto=format&fit=crop&w=150&q=80",
    reviewer: "Clinical Quality Specialist",
    reviewerRole: "Reviewed by:",
    reviewerImage: "",
    showByline: true,
    showAuthor: true,
    showReviewer: true,
    views: 640,
    status: "published",
    publishedAt: "2026-09-02T14:30:00Z",
    seoTitle: "Class B vs Class S Medical Autoclaves UAE Standards",
    seoDescription: "Detailed comparison between Class B and Class S medical steam sterilizers for clinics and surgical centres in UAE."
  },
  {
    id: "blog-4",
    title: "Preventive Maintenance Protocols for ICU Multiparameter Patient Monitors",
    slug: "preventive-maintenance-icu-patient-monitors",
    excerpt: "Best practice biomedical engineering protocols for ECG, SpO2, NIBP calibration, and battery maintenance in intensive care units.",
    content: "Multiparameter monitors provide continuous real-time physiological telemetry. Periodic calibration, sensor integrity inspections, and leakage current testing ensure zero downtime and accurate clinical diagnostic telemetry.",
    featuredImage: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80",
    category: "Biomedical Maintenance",
    tags: ["ICU Monitors", "Biomedical Calibration", "Patient Safety", "Clinical Inspection"],
    author: "FastonMed Biomedical Services",
    authorRole: "Written By",
    authorImage: "",
    reviewer: "Senior Biomedical Engineer",
    reviewerRole: "Reviewed by:",
    reviewerImage: "",
    showByline: true,
    showAuthor: true,
    showReviewer: true,
    views: 310,
    status: "published",
    publishedAt: "2026-08-28T09:15:00Z",
    seoTitle: "ICU Patient Monitor Maintenance & Calibration UAE",
    seoDescription: "Biomedical engineer checklist for preventive maintenance of patient monitors in hospital ICU wards."
  },
  {
    id: "blog-5",
    title: "Guidelines for Selecting Medical Grade Examination & Surgical Gloves in UAE",
    slug: "medical-grade-gloves-selection-guide-uae",
    excerpt: "Nitrile vs Latex vs Vinyl: A guide to barrier protection, AQL pinhole ratings, and chemotherapy-tested nitrile gloves.",
    content: "Healthcare workers require dependable barrier defense. Nitrile examination gloves with AQL 1.5 standards deliver maximum puncture resistance and chemical protection without latex allergen risks.",
    featuredImage: "https://images.unsplash.com/photo-1583947215259-38e31be8751f?auto=format&fit=crop&w=1200&q=80",
    category: "Consumables & PPE",
    tags: ["Medical Gloves", "Nitrile", "Infection Control", "AQL 1.5"],
    author: "Clinical Supplies Unit",
    authorRole: "Written By",
    authorImage: "",
    reviewer: "",
    reviewerRole: "Reviewed by:",
    reviewerImage: "",
    showByline: false,
    showAuthor: true,
    showReviewer: false,
    views: 520,
    status: "published",
    publishedAt: "2026-08-20T11:00:00Z",
    seoTitle: "Medical Gloves Buyer Guide UAE - Nitrile & Latex Standards",
    seoDescription: "Buyer guide to choosing certified medical examination and surgical gloves in UAE hospitals and dental clinics."
  }
];

export const initialPages: PageContent[] = [
  {
    id: 'pg-home',
    title: 'Leading Medical Equipment Supplier in UAE',
    slug: 'home',
    content: 'Fastonmed is a trusted medical equipment supplier in Dubai and across the UAE, offering high-quality healthcare devices, repair services, and training for hospitals, clinics, and labs.',
    status: 'published',
    updatedAt: '2026-09-24T12:00:00Z',
    seoTitle: 'Best Medical Equipment Supplier in UAE | Fastonmed',
    seoDescription: 'Fastonmed is a leading medical equipment supplier in the UAE, providing a wide range of reliable products and services across the United Arab Emirates.'
  },
  {
    id: 'pg-about',
    title: 'About Us',
    slug: 'about-us',
    content: `FastonMed is a premier United Arab Emirates supplier of advanced medical devices, hospital equipment, and biomedical services. Headquartered in Dubai, we serve healthcare institutions across Dubai, Abu Dhabi, Sharjah, Ajman, Ras Al Khaimah, Fujairah, and Umm Al Quwain.

Our certified biomedical engineers provide not only equipment procurement but also turnkey installation, testing, staff clinical training, preventive maintenance, and calibration services.`,
    status: 'published',
    updatedAt: '2026-09-24T12:00:00Z',
    seoTitle: 'About FastonMed Dubai UAE',
    seoDescription: 'Learn about FastonMed, UAE leading medical equipment distributor and biomedical engineering partner.'
  },
  {
    id: 'pg-contact',
    title: 'Contact FastonMed',
    slug: 'contact',
    content: `Get in touch with our medical equipment sales and biomedical engineering teams in UAE.
Phone: +971 50 889 3589 / +971 50 889 3586
Email: sales@fastonmed.com
Office: OFF215 - Arjumand Building, Green Community Village, DIP-1, Dubai, United Arab Emirates.`,
    status: 'published',
    updatedAt: '2026-09-24T12:00:00Z',
    seoTitle: 'Contact FastonMed - Medical Equipment Supplier Dubai UAE',
    seoDescription: 'Contact FastonMed for medical equipment enquiries, quotations, or maintenance services in Dubai & UAE. Call +971 50 889 3589 / +971 50 889 3586.'
  }
];

export const initialStoreSettings: StoreSettings = {
  storeName: 'FastonMed (FASTONMED TRADING L.L.C)',
  supportPhone: '+971 50 889 3589 / +971 50 889 3586',
  salesEmail: 'sales@fastonmed.com',
  whatsappNumber: '+971508893589',
  currency: 'AED',
  vatRate: 5,
  freeShippingThreshold: 500,
  flatShippingRate: 25,
  address: 'OFF215 - Arjumand Building, Green Community Village, DIP-1, Dubai, United Arab Emirates',
  announcementText: '⚙️ Reliable Equipment, Exceptional Care. | 💡 Empowering Healthcare with Precision Technology. | 🔧 Complete Solutions — From Sales to Service.'
};

export const initialRedirects: RedirectRule[] = [
  {
    id: 'red-1',
    sourceUrl: '/shop/?filter_cat=pharmacy-refrigerators',
    destinationUrl: '/product-category/pharmacy-refrigerators',
    statusCode: 301,
    isActive: true,
    hitCount: 42,
    createdAt: '2026-09-01T00:00:00Z'
  },
  {
    id: 'red-2',
    sourceUrl: '/product/haier-refrigerator',
    destinationUrl: '/product/haier-biomedical-hyc-309-pharmacy-refrigerator-2-8c-309-l',
    statusCode: 301,
    isActive: true,
    hitCount: 19,
    createdAt: '2026-09-01T00:00:00Z'
  }
];
